github: [your_github_username]
custom: ["[https://buymeacoffee.com/yourlink](https://buymeacoffee.com/yourlink)", "Crypto Wallet Addresses: USDT (TRC20): T... , BTC: ..."]
# Please paste your actual wallet addresses and links above.
