import json
import os
import config

def clean_and_generate():
    print("🧹 [Step 3] Cleaning & Generating Smart Blocklist...")

    input_path = config.EXPANDED_DATA_FILE
    if not os.path.exists(input_path):
        # Fallback to raw if expanded doesn't exist
        print("⚠️ Expanded data not found, falling back to raw (Assumed Contextual).")
        input_path = config.RAW_DATA_FILE
    
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            # data structure might differ between raw and expanded
            if 'data' in data: # Expanded format
                items = data['data'] # list of {word, type}
            elif 'words' in data: # Raw format
                items = [{"word": w, "type": "CONTEXTUAL"} for w in data['words']]
            else:
                items = []
    except FileNotFoundError:
        print(f"❌ No data found to process.")
        return

    strict_list = set()
    contextual_list = set()

    for item in items:
        w = str(item.get('word', '')).strip().lower()
        t = str(item.get('type', 'CONTEXTUAL')).upper()

        if len(w) < 1: continue # Allow single char emojis if any

        if t == 'STRICT':
            strict_list.add(w)
        else:
            contextual_list.add(w)

    sorted_strict = sorted(list(strict_list))
    sorted_contextual = sorted(list(contextual_list))

    # Generate Dart Code (Class Based)
    dart_content = f"""// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Kashef Smart Data Factory
// Strict Terms: {len(sorted_strict)}
// Contextual Terms: {len(sorted_contextual)}

class SyrianBlocklist {{
  /// [Red List] Immediate Local Block. 
  /// Includes: Drugs, Weapons Sales, Severe Sexual Harassment.
  static const List<String> strictBanList = [
"""
    for w in sorted_strict:
        safe_w = w.replace('"', '\\"').replace('$', '\\$')
        dart_content += f'    "{safe_w}",\n'
    dart_content += "  ];\n\n"

    dart_content += """  /// [Grey List] Requires AI/LLM Confirmation.
  /// Includes: Political Groups (ISIS/HTS), Symbols, Violence keywords.
  static const List<String> contextualWatchlist = [
"""
    for w in sorted_contextual:
        safe_w = w.replace('"', '\\"').replace('$', '\\$')
        dart_content += f'    "{safe_w}",\n'
    dart_content += "  ];\n}\n"


    # Ensure directory exists
    os.makedirs(os.path.dirname(config.DART_OUTPUT_PATH), exist_ok=True)

    with open(config.DART_OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(dart_content)

    print(f"✅ Generated Dart class at {config.DART_OUTPUT_PATH}")
    print(f"📊 Stats: {len(sorted_strict)} Strict, {len(sorted_contextual)} Contextual.")

if __name__ == "__main__":
    clean_and_generate()
